version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: always
    networks:
      - mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    command: mongod --quiet --logpath /dev/null

  server:
    build:
      context: ./server
      target: install-dependencies
    command: npm run start:dev
    networks:
      - mongodb
    ports:
      - '3000:3000'
    volumes:
      - ./server/src:/user/src/app/server/src
    depends_on:
      - mongodb
    env_file:
      - ./server/.env

  # web:
  #   build:
  #     context: ./web
  #     target: install-dependencies
  #   command: npm run start
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - ./web/src:/user/src/app/web/src
  #   depends_on:
  #     - server
  #   env_file:
  #     - ./web/.env

networks:
  mongodb:
    driver: bridge

volumes:
  mongodb:
